# Generated by Django 5.2.7 on 2026-01-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_logentry_logsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
